language: node_js
node_js:
  - '0.10'

before_install:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'

before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'

script: 
  - 'grunt --verbose'

after_success:
  - 'grunt coverage'
  - 'grunt coverage2'